- hosts: all
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  tasks:
    - name: retrieve all the interfaces
      fmgr_fact:
        facts:
            selector: 'system_interface'
            params:
                interface: ''