- name: Interface configuration
  hosts: all
  gather_facts: false
  connection: httpapi
  collections:
    - fortinet.fortimanager
  tasks:
    - name: Retrive all the interfaces
      fmgr_fact:
        access_token: {{ access_token }}
        facts:
          selector: "system_interface"
          params:
            interface: ""