- name: Gathering fortimanager facts
  hosts: all
  gather_facts: false
  connection: httpapi
    - name: Retrive all the interfaces
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "system_interface"
          params:
            interface: ""